[tool.poetry]
name = "braggcalculator"
version = "0.1.0"
description = ""
authors = ["FrederikLizakJohansen <fupjohansen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12,<3.14"
pymatgen = "^2025.6.14"
numpy = "^2.3.2"
spglib = "^2.6.0"
notebook = "^7.4.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
