#!/usr/bin/env python3
"""Generate the version-2 experimental-effects gallery."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import matplotlib
import numpy as np

matplotlib.use("Agg")
from matplotlib import pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from braggcalculator import (  # noqa: E402
    AmorphousHump,
    BackgroundArtifacts,
    BackgroundPattern,
    BraggCalculator,
    CalibrationArtifacts,
    DetectorArtifacts,
    IntensityArtifacts,
    NoiseArtifacts,
    PeakProfileArtifacts,
    PreferredOrientation,
    SimulationArtifacts,
    SpuriousPeakArtifacts,
)


MM_PER_INCH = 25.4
NATURE_DOUBLE_COLUMN_MM = 183.0


def _scaled(values) -> np.ndarray:
    array = np.asarray(values, dtype=float)
    maximum = float(np.max(array, initial=0.0))
    return array if maximum <= 0 else array / maximum


def _illustrative_imported_background() -> BackgroundPattern:
    """Return a deterministic file-style trace, explicitly not measured data."""
    coordinate = np.linspace(10.0, 80.0, 15)
    intensity = (
        0.018
        + 0.012 * np.exp(-0.5 * ((coordinate - 24.0) / 9.0) ** 2)
        + 0.008 * np.exp(-0.5 * ((coordinate - 56.0) / 15.0) ** 2)
    )
    return BackgroundPattern(
        coordinate=coordinate,
        intensity=intensity,
        domain="two_theta",
        source="deterministic illustrative trace generated by plot_artifact_gallery.py",
    )


def artifact_configurations() -> list[tuple[str, str, SimulationArtifacts | None]]:
    """Return every category displayed in the gallery."""
    calibration = SimulationArtifacts(
        calibration=CalibrationArtifacts(
            zero_shift=0.12,
            axis_scale=1.001,
            specimen_displacement_mm=-0.20,
            goniometer_radius_mm=200.0,
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    profile = SimulationArtifacts(
        profile=PeakProfileArtifacts(
            model="tch",
            caglioti_u=0.0025,
            caglioti_v=0.0,
            caglioti_w=0.0064,
            lorentzian_x=0.010,
            lorentzian_y=0.006,
            crystallite_size_nm=20.0,
            microstrain=0.001,
            axial_asymmetry=0.012,
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    intensity = SimulationArtifacts(
        intensity=IntensityArtifacts(
            peak_jitter=(0.90, 1.10),
            peak_dropout_probability=0.02,
            preferred_orientation=PreferredOrientation(
                axis=(0, 0, 1), ratio=0.55, fraction=0.85
            ),
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    background = SimulationArtifacts(
        background=BackgroundArtifacts(
            constant=0.025,
            linear_slope=-0.00025,
            chebyshev_coefficients=(0.012, -0.008, 0.010),
            amorphous_humps=(
                AmorphousHump(center=24.0, fwhm=11.0, height=0.13),
                AmorphousHump(center=55.0, fwhm=18.0, height=0.07, eta=0.25),
            ),
            measured=_illustrative_imported_background(),
            measured_scale=1.0,
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    spurious = SimulationArtifacts(
        spurious_peaks=SpuriousPeakArtifacts(
            count=5,
            intensity=(0.012, 0.035),
            fwhm=(0.12, 0.22),
            eta=(0.2, 0.7),
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    noise = SimulationArtifacts(
        background=BackgroundArtifacts(constant=0.015),
        noise=NoiseArtifacts(
            gaussian_std=0.004,
            correlated_std=0.010,
            correlation_length=0.20,
            poisson_count_scale=1200.0,
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    detector = SimulationArtifacts(
        detector=DetectorArtifacts(
            random_mask_probability=0.012,
            excluded_ranges=((35.0, 37.0), (62.0, 64.0)),
            saturation_level=0.62,
            quantization_step=0.0125,
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    combined = SimulationArtifacts(
        calibration=CalibrationArtifacts(zero_shift=0.08, specimen_displacement_mm=-0.10),
        profile=PeakProfileArtifacts(
            model="tch",
            caglioti_u=0.0025,
            caglioti_w=0.0064,
            lorentzian_x=0.008,
            lorentzian_y=0.004,
            crystallite_size_nm=35.0,
            microstrain=0.0007,
            axial_asymmetry=0.008,
        ),
        intensity=IntensityArtifacts(
            peak_jitter=(0.94, 1.06),
            preferred_orientation=PreferredOrientation((0, 0, 1), ratio=0.72),
        ),
        background=BackgroundArtifacts(
            constant=0.018,
            amorphous_humps=(AmorphousHump(25.0, 12.0, 0.08),),
        ),
        noise=NoiseArtifacts(
            gaussian_std=0.003,
            correlated_std=0.006,
            correlation_length=0.18,
            poisson_count_scale=1800.0,
        ),
        detector=DetectorArtifacts(
            excluded_ranges=((62.0, 63.0),),
            saturation_level=0.82,
            quantization_step=0.00625,
        ),
        spurious_peaks=SpuriousPeakArtifacts(
            count=3, intensity=(0.008, 0.020), fwhm=(0.12, 0.20)
        ),
        normalize_signal=True,
        final_normalize=True,
        domain="two_theta",
        seed=11,
    )
    return [
        ("Ideal reference", "configured Gaussian profile", None),
        ("Calibration", "zero + scale + displacement", calibration),
        ("Peak profile", "TCH + size + strain + tail", profile),
        ("Intensities", "texture + jitter + dropout", intensity),
        ("Background", "analytic + hump + input trace", background),
        ("Spurious peaks", "unindexed pseudo-Voigt lines", spurious),
        ("Noise", "Poisson + white + correlated", noise),
        ("Detector", "gaps + saturation + quantization", detector),
        ("Combined", "representative joint realization", combined),
    ]


def calculate_gallery(cif_path: Path):
    calculator = BraggCalculator(
        mode="xray",
        wavelength="CuKa1",
        two_theta_range=(10.0, 80.0),
        two_theta_step=0.02,
    ).load(cif_path)
    grid, ideal_raw = calculator.pattern()
    ideal = _scaled(ideal_raw)
    results = []
    for title, details, artifacts in artifact_configurations():
        if artifacts is None:
            values = ideal
        else:
            artifact_grid, values = calculator.pattern(artifacts=artifacts)
            np.testing.assert_array_equal(artifact_grid, grid)
            values = _scaled(values)
        results.append((title, details, np.asarray(values, dtype=float)))
    return np.asarray(grid, dtype=float), ideal, results


def plot_gallery(grid, ideal, results, output_stem: Path) -> None:
    plt.rcParams.update(
        {
            "axes.labelsize": 7,
            "axes.linewidth": 0.6,
            "axes.spines.right": False,
            "axes.spines.top": False,
            "axes.titlesize": 7,
            "font.family": "sans-serif",
            "font.sans-serif": ("Arial", "Helvetica", "Liberation Sans", "DejaVu Sans"),
            "font.size": 6.5,
            "legend.fontsize": 6,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "svg.hashsalt": "braggcalculator-artifact-gallery-v2",
            "xtick.labelsize": 6,
            "xtick.major.size": 2.5,
            "xtick.major.width": 0.6,
            "ytick.labelsize": 6,
            "ytick.major.size": 2.5,
            "ytick.major.width": 0.6,
        }
    )
    figure, axes = plt.subplots(
        3,
        3,
        figsize=(NATURE_DOUBLE_COLUMN_MM / MM_PER_INCH, 132.0 / MM_PER_INCH),
        sharex=True,
        sharey=True,
        layout="constrained",
    )
    color = "#0072B2"
    reference_color = "0.70"
    for index, (axis, (title, details, values)) in enumerate(
        zip(axes.flat, results)
    ):
        if title == "Detector":
            for lower, upper in ((35.0, 37.0), (62.0, 64.0)):
                axis.axvspan(lower, upper, color="0.90", linewidth=0, zorder=0)
        if index:
            axis.plot(
                grid,
                ideal,
                color=reference_color,
                linewidth=0.75,
                linestyle="--",
                label="ideal",
                zorder=1,
            )
        axis.plot(grid, values, color=color, linewidth=0.85, label="simulated", zorder=2)
        axis.set_xlim(grid[0], grid[-1])
        axis.set_ylim(-0.035, 1.06)
        axis.set_yticks((0.0, 0.5, 1.0))
        axis.text(
            0.02,
            0.96,
            f"{chr(ord('a') + index)}  {title}",
            transform=axis.transAxes,
            ha="left",
            va="top",
            fontweight="bold",
            fontsize=7,
        )
        axis.text(
            0.98,
            0.96,
            details,
            transform=axis.transAxes,
            ha="right",
            va="top",
            color="0.25",
            fontsize=5.2,
        )
        if index // 3 == 2:
            axis.set_xlabel(r"$2\theta$ (degrees)")
        if index % 3 == 0:
            axis.set_ylabel("Relative intensity")
    axes.flat[1].legend(
        loc="upper center",
        bbox_to_anchor=(0.5, 1.22),
        frameon=False,
        ncol=2,
    )

    output_stem.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_stem.with_suffix(".pdf"))
    figure.savefig(output_stem.with_suffix(".svg"))
    figure.savefig(output_stem.with_suffix(".png"), dpi=450)
    plt.close(figure)


def write_metadata(grid, ideal, results, output_path: Path, cif_path: Path) -> None:
    resolved_cif = Path(cif_path).resolve()
    try:
        cif_record = str(resolved_cif.relative_to(ROOT))
    except ValueError:
        cif_record = str(resolved_cif)
    records = []
    for title, details, values in results:
        records.append(
            {
                "title": title,
                "details": details,
                "maximum": float(np.max(values)),
                "mean": float(np.mean(values)),
                "rms_difference_from_ideal": float(
                    np.sqrt(np.mean((values - ideal) ** 2))
                ),
            }
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "cif": cif_record,
                "domain": "two_theta",
                "range_degrees": [float(grid[0]), float(grid[-1])],
                "step_degrees": float(grid[1] - grid[0]),
                "seed": 11,
                "panels": records,
            },
            indent=2,
        )
        + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cif", type=Path, default=ROOT / "demo" / "NaCl.cif")
    parser.add_argument(
        "--output-stem",
        type=Path,
        default=ROOT / "paper" / "figures" / "artifact_gallery",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=ROOT / "paper" / "data" / "artifact_gallery.json",
    )
    args = parser.parse_args()
    grid, ideal, results = calculate_gallery(args.cif)
    plot_gallery(grid, ideal, results, args.output_stem)
    write_metadata(grid, ideal, results, args.metadata, args.cif)


if __name__ == "__main__":
    main()
